### ISSUE TITLE
Thanks for using my Anti Verizon hosts!

### ISSUE THREAD

**Issue by ghost** [ethan817/Unnecessary-Mobile-Hosts#1]
Thanks for choosing to use my Anti Verizon hosts in `combined pihole exclusive list.txt`, it appears that you have a way older version though. For the best protection I recommend updating / I've recently tested every Verizon app I could find on Android and updated the list a lot.

**Comment by ethan817** [comment]
Sorry for the late response, and thanks for letting me know! Also, please feel free & do not hesitate to let me know if you do not wish your hosts list to be in the list or anything else relating to the use of your lists in my repo.

**Comment by ghost** [comment]
@ethan817 The late response is fine :)

Also, the use of my lists is fine, I really appreciate you using them because it lets me know some people actually use my lists. I've changed the license to "The Unlicense" meaning you have the right to do whatever you want with it because it's public domain.

**Comment by ethan817** [comment]
Awesome, that's great news!
